spring:
  profiles:
    active:
    - dev
---
content: 我是你大爷，狠狠
server:
  port: 2001
spring:
  application:
    name: manage-web-service-brand #微服务的名称
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Shanghai
    username: root
    password: Xu1234567@
mybatis:
  type-aliases-package: entity
  mapper-locations: classpath:mapper/*Mapper.xml
pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
---
content: 嘿嘿嘿
server:
  port: 2001
spring:
  application:
    name: manage-web-service-brand #微服务的名称
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Shanghai
    username: root
    password: Xu1234567@
mybatis:
  type-aliases-package: entity
  mapper-locations: classpath:mapper/*Mapper.xml
pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
